services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - network_f
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - network_f
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - network_f
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_volume:
    driver: local
  wordpress_volume:
    driver: local

networks:
  network_f:
    driver: bridge

